# Generated by Django 2.2.28 on 2022-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0authorization', '0002_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probability',
            name='decay_rate',
            field=models.FloatField(default=0.01),
        ),
        migrations.AlterField(
            model_name='probability',
            name='probability_random',
            field=models.FloatField(default=0.95),
        ),
    ]
